services:
  spi_service:
    image: debian:bookworm-slim
    user: root
    devices:
      - /dev/spidev0.0
    # published on the board instead of only compose so other services can communicate
    ports:
      - "9000:9000"
    volumes:
      - .:/spi_service
    command: >
      sh -c "apt update &&
             apt install -y python3 python3-spidev &&
             python3 /spi_service/spi_service.py"